[project]
name = "life-os"
version = "0.1.0"
description = ""
authors = [{name = "harish", email = "popitlikepopcorn@gmail.com"}]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "schedule>=1.2.2",
]
