---
intel_scout:
  capabilities:
    - technology
    - business
game_theorist:
  capabilities:
    - strategy
    - planning
    - learning
    - financial
ops_planner:
  capabilities:
    - operations
    - coordination
    - wellness
    - habit