
# Life OS Protocol Configuration
# Defines the systematic approaches for different life domains

planning_protocol:
  name: "Strategic Life Planning Protocol"
  description: "Systematic approach to life planning with go/no-go gates"
  trigger_conditions:
    - new_opportunity_detected
    - quarterly_review_due
    - major_life_change
  go_no_go_criteria:
    - has_clear_objectives: true
    - resources_available: true
    - aligned_with_worldview: true
    - asymmetric_upside: true
  steps:
    1: "Assess current position (SWOT analysis)"
    2: "Define clear objectives and KPIs"
    3: "Resource allocation analysis"
    4: "Risk assessment and hedge planning"
    5: "Execution timeline with milestones"
    6: "Contingency planning"
  success_metrics:
    - plan_quality_score: ">= 4.0"
    - resource_efficiency: ">= 85%"
    - risk_mitigation_coverage: ">= 90%"

research_protocol:
  name: "Intelligence Gathering Protocol"
  description: "Systematic approach to gathering actionable intelligence"
  frequency: "daily"
  domains:
    - financial_markets
    - technology_trends
    - geopolitical_developments
    - business_opportunities
    - social_dynamics
  go_no_go_criteria:
    - information_quality: "high"
    - actionability: true
    - relevance_to_goals: true
  outputs:
    - daily_intelligence_brief
    - opportunity_alerts
    - threat_assessments
    - asymmetric_bets_identified

preparation_protocol:
  name: "Preparation and Positioning Protocol"
  description: "Ensure proper preparation before any execution"
  mandatory_checks:
    - planning_completed: true
    - resources_secured: true
    - risks_hedged: true
    - success_criteria_defined: true
  preparation_phases:
    1: "Resource acquisition and allocation"
    2: "Skill and knowledge preparation"
    3: "Network and relationship preparation"
    4: "Risk mitigation setup"
    5: "Success metrics definition"

execution_protocol:
  name: "Execution and Monitoring Protocol"
  description: "Systematic approach to task execution and progress monitoring"
  execution_principles:
    - relentless_resourcefulness: true
    - continuous_monitoring: true
    - adaptive_adjustment: true
    - leverage_optimization: true
  monitoring_frequency: "real_time"
  adjustment_triggers:
    - performance_deviation: "> 20%"
    - new_information: "high_impact"
    - resource_constraints: "critical"

war_gaming_protocol:
  name: "Strategic War Gaming Protocol"
  description: "Daily strategic analysis and scenario planning"
  frequency: "daily"
  analysis_frameworks:
    - game_theory_analysis
    - scenario_planning
    - competitive_dynamics
    - opportunity_cost_analysis
  decision_criteria:
    - expected_value_calculation
    - asymmetric_risk_reward
    - optionality_preservation
    - antifragility_enhancement

negotiation_protocol:
  name: "Negotiation and Diplomacy Protocol"  
  description: "Systematic approach to negotiations and relationship management"
  preparation_phase:
    - counterparty_analysis
    - batna_development
    - leverage_assessment
    - value_creation_opportunities
  execution_phase:
    - relationship_building
    - information_gathering
    - value_proposition_presentation
    - collaborative_problem_solving
  success_metrics:
    - win_win_achievement: true
    - relationship_preservation: true
    - long_term_value_creation: true
